version: '2'

services:
          
  database:
    image: 'postgres:13.1-alpine'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=serverstop-app
      - POSTGRES_PASSWORD=serverstop123
